### ISSUE TITLE
remaining bug on friday

### ISSUE THREAD

**Issue by ajkim0630** [ajkim0630/practice-problems#2]

**Comment by ajkim0630** [comment]
friday

  Here are the respective outputs:
        ----- our output ---------
        9_9_7_9_9_8_9
        ---- your output ---------
        9_9_8_9_9_8_8
        --------------------------

        ------ Data for Run 3 [length=2 bytes] ------
        5 
        ----------------------------

        Your program printed data to stdout.  Here is the data:
        -------------------
        YEAR:__1990
        YEAR:__1991
        YEAR:__1992
        YEAR:__1993
        YEAR:__1994

**Comment by jybluekim** [comment]
I did some quick debug and it's weird. I have a feeling that we are right and USACO is wrong??

Here is the trace I generated. I verified all of this on a calendar. There are 8 valid 13th Monday. 

BTW I cannot follow the link b/c I need a login. I wonder if there is some fine print you missed??

jkim@DESKTOP-K83GNLP MINGW64 ~/PycharmProjects/Practice
$ grep 13 friday.log  | grep mon
1990 August 13 mon
1991 May 13 mon
1992 January 13 mon
1992 April 13 mon
1992 July 13 mon
1993 September 13 mon
1993 December 13 mon
1994 June 13 mon

**Comment by jybluekim** [comment]
Why was this closed? I don't see anything

**Comment by ajkim0630** [comment]
I fixed it

**Comment by ajkim0630** [comment]
there was a problem with the leap years but I added 

"if i % 400 == 0: 
howmanydays = 29
else:
howmanydays = 28

**Comment by ajkim0630** [comment]
"

**Comment by jybluekim** [comment]
Yeah turns out that you did not read the problem thoroughly!
