### ISSUE TITLE
[Subset] Write the code that works w/o memoization 

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/practice-problems#20]
I want to separate dynamic programming or memoization from solving this problem. 

So I want to say first write your code so that it will work for relatively small number (say n <= 20). Remember n is supposed to go up to 39 and for numbers in the 30's, you would certainly want memoization to work for performance.

**Comment by ajkim0630** [comment]
done, a5f02a64341b865c472e9c7fa4ba966fbff79a3e fixes it
