### ISSUE TITLE
[Subset] Add memoization 

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/practice-problems#21]
Once you have a working prototype w/o memoization, then add a way to "cache" previously calculated answers for performance. Should be straightforward.

**Comment by ajkim0630** [comment]
Here are the test data inputs:

------- test 1 [length 3 bytes] ----
99
------- test 2 [length 7 bytes] ----
111110
------- test 3 [length 7 bytes] ----
134259
------- test 4 [length 7 bytes] ----
348761
------- test 5 [length 8 bytes] ----
1000000
------- test 6 [length 8 bytes] ----
5000000
------- test 7 [length 8 bytes] ----
9000000
