### ISSUE TITLE
[Lamps] Add support for 3x button

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/practice-problems#28]
Do this after you finish #27 (support for ALL button).

Now finally add support for the 4th button which flips every 3rd lamp. In 1-based world like the problem, this means lamp 1, 4, 7, etc. If you are doing 0-based counting, then it will be 0, 3, 6, etc. 

So with 4 buttons, you might have a bit more complexity to deal with but it should be doable. 

Have fun!

**Comment by ajkim0630** [comment]
done
