### ISSUE TITLE
Input/output file handling 

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/practice-problems#34]
So what I have seen is that you write code like this, which means every problem uses the same input/output file name.

I understand that you need to do this for submission but I also want to capture some inputs for the future. So here is my suggestion. Use a variable to switch file names between development and submission. Create a new file for your development (in this case: prefix.in.txt) and have it checked in. Do this for all subsequent problems. 

BEFORE:

```
if __name__ == '__main__':
    inputs = []
    with open ('in.txt','r') as f:
        for i in f:
            n = i.rstrip()
            inputs.append(n)

```

NEW: 
```
if __name__ == '__main__':
    inputs = []

   # set to True when you submit to USACO
    SUBMIT = False
     infile = ""

    if SUBMIT: infile= 'in.txt'
    else: inf = "prefix.in.txt"

    with open (infile, 'r') as f:
        for i in f:
            n = i.rstrip()
            inputs.append(n)
```

**Comment by ajkim0630** [comment]
done

**Comment by jybluekim** [comment]
You got it backwards; re-opening.

**Comment by jybluekim** [comment]
So just to reiterate on the purpose of this is... I want to capture as many test cases as possible. So if different problems have different input files names - that is awesome and we should keep them in the repo. You should also check in new versions (as there are multiple problems). 
Somehow I thought the input file names are the same for _all_ USACO problems. If they are unique, keep them unique. If they happen to be the same then keep them unique at least during your development.

**Comment by ajkim0630** [comment]
done
